version: "3"
services:
  db:
    image: postgres:16
    networks:
      - hmpps
    container_name: custody-manager-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=custody-manager
      - POSTGRES_PASSWORD=custody-manager
      - POSTGRES_USER=custody-manager

  localstack:
    image: localstack/localstack:latest
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4567:4566"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DELIUS_ENABLED=false

networks:
  hmpps:
