---
# Per environment values which override defaults in hmpps-custody-manager-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: court-cases-release-dates-api-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-custody-manager-api-cert

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

  # Used to access resources like S3 buckets, SQS queues and SNS topics
  serviceAccountName: hmpps-custody-manager-api

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts-non-prod
  businessHoursOnly: true
